#!/bin/sh


die() {
  echo >&2 "$@"
  exit 1
}

[ "$#" -eq 12 ] || die "$BASH_SOURCE requires 12 arguments"

OUTPUT_NLCD_NAME=$1
OUTPUT_AWC_NAME=$2
OUTPUT_SOILS_NAME=$3
OUTPUT_D8_FLOWDIR_NAME=$4
OUTPUT_SWB_CTL_NAME=$5
LLX=$6
LLY=$7
NX=$8
NY=$9
RES=${10}
START_DATE=${11}
END_DATE=${12}

echo """GRID $NX $NY $LLX $LLY $RES
BASE_PROJECTION_DEFINITION +proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=23.0 +lon_0=-96.0 +x_0=0.0 +y_0=0.0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs

## DEFINE METHODS TO BE USED ##

INTERCEPTION_METHOD              BUCKET
EVAPOTRANSPIRATION_METHOD        HARGREAVES
RUNOFF_METHOD                    CURVE_NUMBER
SOIL_MOISTURE_METHOD             THORNTHWAITE
FLOW_ROUTING_METHOD              D8
IRRIGATION_METHOD                NONE
CROP_COEFFICIENT_METHOD          NONE

INITIAL_PERCENT_SOIL_MOISTURE    CONSTANT 50.0
INITIAL_SNOW_COVER_STORAGE       CONSTANT 0.0
IRRIGATION_MASK                  CONSTANT 1

PRECIPITATION NETCDF /home/nobody/COMMON_CLIMATE/Daymet_2015/prcp_%Y.nc4
PRECIPITATION_GRID_PROJECTION_DEFINITION +proj=lcc +lat_1=25.0 +lat_2=60.0 +lat_0=42.5 +lon_0=-100.0 +x_0=0.0 +y_0=0.0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs
PRECIPITATION_NETCDF_Z_VAR             prcp
PRECIPITATION_NETCDF_FLIP_VERTICAL
PRECIPITATION_CONVERSION_FACTOR  0.03936996
PRECIPITATION_MISSING_VALUES_CODE       0.0
PRECIPITATION_MISSING_VALUES_OPERATOR     <
PRECIPITATION_MISSING_VALUES_ACTION    ZERO


TMAX NETCDF /home/nobody/COMMON_CLIMATE/Daymet_2015/tmax_%Y.nc4
TMAX_GRID_PROJECTION_DEFINITION +proj=lcc +lat_1=25.0 +lat_2=60.0 +lat_0=42.5 +lon_0=-100.0 +x_0=0.0 +y_0=0.0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs
TMAX_NETCDF_FLIP_VERTICAL
TMAX_SCALE_FACTOR                 1.8
TMAX_ADD_OFFSET                  32.0
TMAX_MISSING_VALUES_CODE      -9999.0
TMAX_MISSING_VALUES_OPERATOR      <=
TMAX_MISSING_VALUES_ACTION       mean

TMIN NETCDF /home/nobody/COMMON_CLIMATE/Daymet_2015/tmin_%Y.nc4
TMIN_GRID_PROJECTION_DEFINITION +proj=lcc +lat_1=25.0 +lat_2=60.0 +lat_0=42.5 +lon_0=-100.0 +x_0=0.0 +y_0=0.0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs
TMIN_NETCDF_FLIP_VERTICAL
TMIN_SCALE_FACTOR                 1.8
TMIN_ADD_OFFSET                  32.0
TMIN_MISSING_VALUES_CODE      -9999.0
TMIN_MISSING_VALUES_OPERATOR      <=
TMIN_MISSING_VALUES_ACTION       mean

FLOW_DIRECTION ARC_GRID $OUTPUT_D8_FLOWDIR_NAME
FLOW_DIRECTION_PROJECTION_DEFINITION +proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=23.0 +lon_0=-96.0 +x_0=0.0 +y_0=0.0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs

HYDROLOGIC_SOILS_GROUP ARC_GRID $OUTPUT_SOILS_NAME
HYDROLOGIC_SOILS_GROUP_PROJECTION_DEFINITION +proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=23.0 +lon_0=-96.0 +x_0=0.0 +y_0=0.0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs

AVAILABLE_WATER_CONTENT ARC_GRID $OUTPUT_AWC_NAME
AVAILABLE_WATER_CONTENT_PROJECTION_DEFINITION +proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=23.0 +lon_0=-96.0 +x_0=0.0 +y_0=0.0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs

LAND_USE ARC_GRID $OUTPUT_NLCD_NAME
LAND_USE_PROJECTION_DEFINITION +proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=23.0 +lon_0=-96.0 +x_0=0.0 +y_0=0.0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs

LAND_USE_LOOKUP_TABLE /home/nobody/Project_Data/GLASS/swb_input/LU_LOOKUP_NLCD_QA_SM__SWB2.txt

START_DATE $START_DATE
END_DATE $END_DATE
""" > "$OUTPUT_SWB_CTL_NAME"