#!/bin/sh


die() {
  echo >&2 "$@"
  exit 1
}

[ "$#" -eq 12 ] || die "$BASH_SOURCE requires 12 arguments"

OUTPUT_NLCD_NAME="${1}"
OUTPUT_AWC_NAME="${2}"
OUTPUT_SOILS_NAME="${3}"
OUTPUT_D8_FLOWDIR_NAME="${4}"
OUTPUT_SWB_CTL_NAME="${5}"
LLX="${6}"
LLY="${7}"
NX="${8}"
NY="${9}"
RES=${10}
START_DATE=${11}
END_DATE=${12}

echo """GRID $NX $NY $LLX $LLY $RES
BASE_PROJECTION_DEFINITION +proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=23.0 +lon_0=-96.0 +x_0=0.0 +y_0=0.0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs
GRID_LENGTH_UNITS METERS

SUPPRESS_SCREEN_OUTPUT
#SUPPRESS_INTEGRATED_OUTPUT
SUPPRESS_DAILY_FILES
SUPPRESS_DISLIN_MESSAGES

GROWING_SEASON 133 268 TRUE

RLE_MULTIPLIER 10000

INITIAL_ABSTRACTION_METHOD HAWKINS

INITIAL_SOIL_MOISTURE            CONSTANT 50.0
INITIAL_SNOW_COVER               CONSTANT 0.0

INITIAL_FROZEN_GROUND_INDEX CONSTANT 100.0
UPPER_LIMIT_CFGI 83.
LOWER_LIMIT_CFGI 55.

OPEN_WATER_LAND_USE 11

SM T-M EQUATIONS
INTERCEPTION_METHOD HORTON

RUNOFF C-N NO_ROUTING
ET HARGREAVES 38.77 42.44

PRECIPITATION NETCDF /home/nobody/COMMON_CLIMATE/Daymet_2015/prcp_%Y.nc4
PRECIPITATION_GRID_PROJECTION_DEFINITION +proj=lcc +lat_1=25.0 +lat_2=60.0 +lat_0=42.5 +lon_0=-100.0 +x_0=0.0 +y_0=0.0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs
NETCDF_PRECIP_Z_VAR                    prcp
NETCDF_PRECIP_FLIP_VERTICAL
PRECIPITATION_SCALE_FACTOR            0.03936996
PRECIPITATION_MISSING_VALUES_CODE       0.0
PRECIPITATION_MISSING_VALUES_OPERATOR     <
PRECIPITATION_MISSING_VALUES_ACTION    ZERO


TEMPERATURE NETCDF /home/nobody/COMMON_CLIMATE/Daymet_2015/tmax_%Y.nc4 /home/nobody/COMMON_CLIMATE/Daymet_2015/tmin_%Y.nc4
TMAX_GRID_PROJECTION_DEFINITION +proj=lcc +lat_1=25.0 +lat_2=60.0 +lat_0=42.5 +lon_0=-100.0 +x_0=0.0 +y_0=0.0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs
NETCDF_TMAX_FLIP_VERTICAL
TMAX_SCALE_FACTOR                 1.8
TMAX_ADD_OFFSET                  32.0
TMAX_MISSING_VALUES_CODE      -9999.0
TMAX_MISSING_VALUES_OPERATOR      <=
TMAX_MISSING_VALUES_ACTION       MEAN

TMIN_GRID_PROJECTION_DEFINITION +proj=lcc +lat_1=25.0 +lat_2=60.0 +lat_0=42.5 +lon_0=-100.0 +x_0=0.0 +y_0=0.0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs
NETCDF_TMIN_FLIP_VERTICAL
TMIN_SCALE_FACTOR                 1.8
TMIN_ADD_OFFSET                  32.0
TMIN_MISSING_VALUES_CODE      -9999.0
TMIN_MISSING_VALUES_OPERATOR      <=
TMIN_MISSING_VALUES_ACTION       MEAN

FLOW_DIRECTION ARC_GRID $OUTPUT_D8_FLOWDIR_NAME
HYDROLOGIC_SOIL_GROUP ARC_GRID $OUTPUT_SOILS_NAME
WATER_CAPACITY  ARC_GRID $OUTPUT_AWC_NAME
LAND_USE ARC_GRID $OUTPUT_NLCD_NAME

LAND_USE_LOOKUP_TABLE /home/nobody/Project_Data/GLASS/swb_input/LU_LOOKUP_NLCD_QA__SWB1.txt

#*******************************************************************
# PLOTTING CUSTOMIZATION
#
# This version of the SWB model allows very limited assignment of
# DISLIN plotting parameters for the generation of images.
# See http://www.mps.mpg.de/dislin/ for more information about this
# package.
#
# If no customizations are specified, default values will be used.
#
#DISLIN_PARAMETERS RECHARGE
#SET_Z_AXIS_RANGE DAILY 0 1.5 0.1
#SET_Z_AXIS_RANGE MONTHLY 0 7 1.0
#SET_Z_AXIS_RANGE ANNUAL 0 20 2.
#Z_AXIS_TITLE RECHARGE, IN INCHES
#
#DISLIN_PARAMETERS ACT_ET
#SET_Z_AXIS_RANGE DAILY 0 0.8 0.05
#SET_Z_AXIS_RANGE MONTHLY 0 10. 0.5
#SET_Z_AXIS_RANGE ANNUAL 0 40. 5.0
#SET_DEVICE PDF
#SET_FONT Helvetica-Bold
#Z_AXIS_TITLE ACTUAL ET, IN INCHES
#
#DISLIN_PARAMETERS POT_ET
#SET_Z_AXIS_RANGE DAILY 0 0.8 0.05
#SET_Z_AXIS_RANGE MONTHLY 0 10. 0.5
#SET_Z_AXIS_RANGE ANNUAL 0 45. 5.
#SET_DEVICE WMF
#SET_FONT Courier New Italic
#Z_AXIS_TITLE POTENTIAL ET, IN INCHES
#
#DISLIN_PARAMETERS RUNOFF_OUTSIDE
#SET_Z_AXIS_RANGE DAILY 0 5. 0.5
#SET_Z_AXIS_RANGE MONTHLY 0 12. 0.5
#SET_Z_AXIS_RANGE ANNUAL 0 25. 5.
#Z_AXIS_TITLE RUNOFF OUT OF GRID, IN INCHES
#
#DISLIN_PARAMETERS SNOWCOVER
#SET_Z_AXIS_RANGE DAILY 0 12. 0.5
#Z_AXIS_TITLE SNOW COVER, IN INCHES (WATER EQUIVALENT)
#
#DISLIN_PARAMETERS SM_APWL
#SET_Z_AXIS_RANGE DAILY -20. 0. 2.0
#Z_AXIS_TITLE ACCUMULATED POTENTIAL WATER LOSS, IN INCHES
#SET_COLOR_TABLE RRAIN

OUTPUT_PATH
OUTPUT_MONTHLY_PATH
OUTPUT_DAILY_PATH
OUTPUT_ANNUAL_PATH
OUTPUT_FUTURE_PATH

IMAGE_PATH
IMAGE_ANNUAL_PATH
IMAGE_DAILY_PATH
IMAGE_MONTHLY_PATH

#OUTPUT_OPTIONS AVG_TEMP NONE GRID GRID
OUTPUT_OPTIONS GROSS_PRECIP NONE NONE GRID

OUTPUT_OPTIONS REJECTED_RECHARGE NONE NONE GRID
OUTPUT_OPTIONS RECHARGE NONE NONE GRID
#OUTPUT_OPTIONS SOIL_MOISTURE NONE NONE GRID
#OUTPUT_OPTIONS CHG_IN_SOIL_MOIS NONE NONE NONE

#OUTPUT_OPTIONS SNOWCOVER NONE NONE NONE
#OUTPUT_OPTIONS CFGI NONE GRID GRID

#OUTPUT_OPTIONS OUTFLOW NONE NONE NONE
OUTPUT_OPTIONS RUNOFF_OUTSIDE NONE NONE GRID
#OUTPUT_OPTIONS INFLOW NONE NONE NONE
#OUTPUT_OPTIONS SM_SURPLUS NONE GRID GRID

OUTPUT_OPTIONS ACT_ET NONE NONE GRID
#OUTPUT_OPTIONS REFERENCE_ET NONE NONE GRID
#OUTPUT_OPTIONS SM_APWL NONE NONE NONE

SOLVE_NO_TS_FILE $START_DATE $END_DATE
EOJ
""" > "$OUTPUT_SWB_CTL_NAME"
